# Generated by Django 5.0.3 on 2024-04-11 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_student_id_student_gender_alter_student_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('course', models.CharField(choices=[('BTech CSE', 'BTech Computer Science & Engineering'), ('Civil', 'Civil Engineering'), ('Law', 'Law')], max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10, null=True)),
                ('date', models.DateField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.subject')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], max_length=1, null=True)),
                ('phoneNO', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(null=True, upload_to='teacher_images/')),
                ('date_of_birth', models.DateField(null=True)),
                ('subjects', models.ManyToManyField(blank=True, to='login.subject')),
            ],
        ),
    ]
