# Generated by Django 5.0.3 on 2024-04-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_attendance_semester_student_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='study_materials')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='materials',
            field=models.ManyToManyField(blank=True, to='login.files'),
        ),
    ]
