# Generated by Django 5.0.3 on 2024-04-21 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_remove_mark_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='login.student'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_marks', to='login.subject'),
        ),
        migrations.AlterField(
            model_name='result',
            name='marks',
            field=models.ManyToManyField(blank=True, related_name='result_marks', to='login.mark'),
        ),
        migrations.AlterField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='login.student'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'semester')},
        ),
    ]
